version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: hexo
    versions:
    - 5.3.0
  - dependency-name: hexo-renderer-marked
    versions:
    - 3.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: hexo-deployer-git
    versions:
    - 2.1.0
