language: node_js
node_js: node
secure: "ntPoOY8Zd7Plq4FXBnMjlviHqNc68Z1iqkIInClKlRtB5MHZ9ncZ9vUgPdsHJlJXYpwEnrsk71bAiSmX16sMn9DnOpropiRuRqdwnv13+DvaEqCk8fKsumWn6/1H33ME2WkNZNHNqYNZ6mm0HM0jresf69mYVQByW91KNoOBr+4kjeC+3GFX0isW61ndGXj1iPj7+cU0hDGmJU2bZ2iUo1lLMmN3nLk2fLnFKLWTZRn+Xqskc2+JNV0mviTOX1qum44uabF4+WA4AQjm20X2qpVHtVt4ui/haHOyEzQTsgalrJA6q9oUW5XbH44CWtP43utOBX+2PSfmTlmwEp+Bb7dSvz0gxYSsZ65hNjXuvAILW4pG0ZJE6DslE19PatdOceaxKJfNfZAx7G3E7Zp5pJtSFG9cGGDq47d3ZBvXOdLAUrRQ2mrqTEf2FMUsb3RohbsAghX5dEQt3wuXs/mthGNCcJHIacBrY64MFc+m/whOC9i2Dfwl4sOoLnkIE9jD7leQeHeMx3LNKtgxUeNRfE7/C3lnd0C/RBecY+5/2CgAn5X2oZx55QN7ANWegSMBSsn5iQ3Z7Cl7HBXNe9ul/RC6L7gbCfwheVUC3Aj5d4Bu38ty+6KBPr9p/nekE40JHy8mvMoAjYgRC2yV0wP2let7zWIgh2BpsUUTfJ0ZWZE="
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages
  local_dir: public/