language: node_js
node_js: node
after_install:
  - openssl aes-256-cbc -K $encrypted_4d3e976819ff_key -iv $encrypted_4d3e976819ff_iv -in id_rsa.enc -out .ci-files/id_rsa -d
  - mv .ci-files/id_rsa ~/.ssh/
  - cat ~/.ssh/config
script:
  - hexo deploy