language: node_js
node_js: node
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "gqSl2VODtLDY8O8yeuHDTgJt0KIh+S7cuDfOlocYHFEPXYMSYdxaxVr4bnxG53nY3fDiPek1zkwvOuu/rZNRrip35RLPLIcLyYKlhoje5dN29jx/3I0D1ck/O0S3uryDaOoMZz8Xjd/2Jkmllr3hJh3TcpL1mJbj7r/DX/WFmL0MyetytP8je/2+KwzqlaZYRVuLYJq2fEsTNO+x/br+WGXqxJ30ZmpHO9X3KJW6rnvelXM9/W5gt8YwyKRM6TL5NovGACSesmu99mO9MIbFN/DzYlSj0uIOliiqoR2SmNHpyh6jSUNK057lV2cioJkfA2JEYQ+67QgfLI3dt0LPjgzyZryEk5ni85LWziunSFXGTPWd4p9mdd4H2uSODZVjb6uMU5zZIfMAQ4MlkXlkP2Ecs5L6VKINBtI5q22Hgma6mphu8wtM0VSQN2cvDJCiyRKHEc8jz7Q9X01jalC+xkYz6/jjEbqNBLgOZTxxATjuKflDlfuZMAPEGYTWfPqbI9kM3hCD4MX97i8m92FweUZ0Y0mBZQ+mSreFftA+L2MDP+VpYg3EnKpXZaKODQPhRgPah/YGw0IzsUkeHTWfnxwbE1Q0s+wWb4ePeifbKKEtg+Z5NUgm1nluq984kIPQAsPOivkqT3vaDk7uSydnqCxch7T4nH0hV9SQFnDrLzU="
  on:
    branch: master
  local_dir: public/
  email: 6533808+rinsuki@users.noreply.github.com
  name: Travis CI Deploy